baseURL = "https://daebfcg.github.io/"
languageCode = "en-us"
title = "DAEBFCG"
theme = "hugo-theme-tokiwa"
author = "DAEBFCG"
enableGitInfo = true
enableEmoji = true
pluralizelisttitles = false
hasCJKLanguage = false

[params]
brand = "DAEBFCG" # name of your site - appears in the sidebar
description = "Luthiery and Musical Projects"
useChineseFonts = false
author = "DAEBFCG"
authorEmail = "you@example.com"

[menu]
# Shown in the side menu.
  [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "post"
    url = "/posts/"
  [[menu.main]]
    name = "Series"
    weight = 1
    identifier = "series"
    url = "/series/"
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 1
  # [[menu.main]]
  #   name = "About"
  #   url = "/about/"
  #   weight = 2


rss_icon = true
rss_section = "posts"

[taxonomies]
series = 'series'
tags = 'tags'

[outputs]
home = ["HTML", "RSS"]

[services]
[services.rss]
limit = 10
feedTitle = "DAEBFCG"
feedDescription = "Luthiery and Musical Projects"
feedLink = "https://daebfcg.github.io/"
feedLanguage = "en-us"

[pagination]
pagerSize = 10

[module]
[[module.imports]]
  path = "github.com/heyeshuang/hugo-theme-tokiwa"
